### PR TITLE
add pixel robotics

### PR DESCRIPTION
**Pull request by tonynajjar**
See https://discourse.ros.org/t/ros-robotics-companies/27252. I thought it wouldn't hurt to add ourselves.

The snippet I used is the same @ValentinPl gave me to pass on to Steve for ROScon.
When was Pixel founded?

### CODE REVIEW

**Comment by jplapp** [comment]
nice find!

**Comment by tonynajjar** [comment]
> It'd be great though for it to include how you guys are using ROS and which version/packages, etc.

I got this feedback from the maintainer, Is this something we want to disclose?

**Comment by jplapp** [comment]
maybe:

Pixel Robotics was one of the first companies to use ROS2 in a production environment, and is proud to actively contribute to the stack.

I wouldn't want to disclose packages further, in this list I don't see this information for any other entry

**Comment by tonynajjar** [comment]
> and is proud to actively contribute to the stack.

nice, I can link the tricycle controller

**Comment by tonynajjar** [comment]
@jplapp @ValentinPl ready for review again.

image

**Pull request merged**
